### ISSUE TITLE
Handle all compatibility branching in a compat.py

### ISSUE THREAD

**Issue by jpadilla** [progrium/pyjwt#67]
I'd like to add a `compat.py` to handle all compatibility branching in one place, removing any of that clutter from the actual code.

**Comment by jpadilla** [comment]
- prepare_key_methods
- signing_methods
- verify_methods
- constant_time_compare

Perhaps also handling of `.total_seconds()` should also go here.

**Comment by wbolster** [comment]
While you're at it, drop usage of `unicode_literals` as well. :) https://github.com/PythonCharmers/python-future/issues/22
