### ISSUE TITLE
usage of unicode_literals breaks "import *"

### ISSUE THREAD

**Issue by wbolster** [progrium/pyjwt#73]
As mentioned in #67, `unicode_literals` is evil in code that needs to work unchanged in Python 2 and Python 3.

I know that `import *` is an anti-pattern, but this is an example of what breaks because of `unicode_literals` in Python 2:

```
>>> from jwt import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Item in ``from list'' not a string
```

Other tools using `__all__` (IDEs perhaps? I don't use those) will likely break as well.

**Comment by mark-adams** [comment]
Which specific version of Python does that happen in?

**Comment by mark-adams** [comment]
Nevermind, I got it in 2.7.

**Comment by wbolster** [comment]
The source of the problem is that the `unicode_literals` future import makes it impossible to use "native strings" in the module, and since "native strings" are used all over the place in Python, this causes all kinds of weird errors.

**Comment by mark-adams** [comment]
I'm also going to go ahead and mention the article you linked to in #67, since it seems to provide a good discussion on the issue: https://github.com/PythonCharmers/python-future/issues/22

**Comment by jpadilla** [comment]
Anything happen when we remove `unicode_literals`?

**Comment by wbolster** [comment]
Don't think so, since the API doesn't have any str/unicode default args or return values, afaics.

**Comment by jpadilla** [comment]
@wbolster nothing seemed to happen in #75.

**Comment by jpadilla** [comment]
Closed via 6a0f184ffafe36466cb9c50feabcbd1c66d06754

**Comment by wbolster** [comment]
for reference, this was fixed via #76

**Comment by merwok** [comment]
For the record, one can use the ``b'string of bytes'`` syntax in 2.6+ to have “native strings” in a module with unicode literals enabled.

**Comment by wbolster** [comment]
No, because it would result in bytes on Python 3, and those are not native strings.

"Éric Araujo" <notifications@github.com> schreef op 23 maart 2015 20:28:29 CET:
>For the record, one can use the ``b'string of bytes'`` syntax in 2.6+
>to have “native strings” in a module with unicode literals enabled.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jpadilla/pyjwt/issues/73#issuecomment-85158759

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mark-adams** [comment]
Isn't this resolved already? :smile:
